version: "3.8"
services:
  nginx:
    container_name: star_nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  php:
    container_name: star_php
    build: ./docker/php
    links:
      - mysql
    ports:
      - "9000:9000"
      - "5176:5176"
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=star
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  mysql:
    image: mysql:8.0.31
    container_name: star_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'star'
      MYSQL_DATABASE: 'star'
      MYSQL_USER: 'star'
      MYSQL_PASSWORD: 'star'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

